### ISSUE TITLE
Actualización de dependencias

### ISSUE THREAD

**Issue by davidv99** [freddiegar/base#1]
Hola Fredi.

Estuve revisando un poco tu librería, pero veo que tienes acopladas unas dependencias en cuanto a algunas versionas de iluminate en el composer json por lo que al momento de querer actualizar la versión de laravel no puedo hacerlo por lo mismo, es posible eliminar esas dependencias para poder actualizar el proyecto autodeclaraciones?

Muchas gracias

**Comment by freddiegar** [comment]
El repo se transfiere
